[package]
name = "rust_pentest_automation"
version = "0.1.0"
edition = "2021"
author = "marcidon"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
